// Code generated by protoc-gen-go.
// source: proximo.proto
// DO NOT EDIT!

/*
Package proximo is a generated protocol buffer package.

It is generated from these files:
	proximo.proto

It has these top-level messages:
	Message
	Request
	StartRequest
	Confirmation
	Config
*/
package proximo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Request struct {
	// expected if this is a start request
	StartRequest *StartRequest `protobuf:"bytes,2,opt,name=startRequest" json:"startRequest,omitempty"`
	// expected if this is a confirmation
	Confirmation *Confirmation `protobuf:"bytes,3,opt,name=confirmation" json:"confirmation,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetStartRequest() *StartRequest {
	if m != nil {
		return m.StartRequest
	}
	return nil
}

func (m *Request) GetConfirmation() *Confirmation {
	if m != nil {
		return m.Confirmation
	}
	return nil
}

type StartRequest struct {
	Topic    string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	Consumer string `protobuf:"bytes,2,opt,name=consumer" json:"consumer,omitempty"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StartRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *StartRequest) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

type Confirmation struct {
	MsgID string `protobuf:"bytes,1,opt,name=msgID" json:"msgID,omitempty"`
}

func (m *Confirmation) Reset()                    { *m = Confirmation{} }
func (m *Confirmation) String() string            { return proto.CompactTextString(m) }
func (*Confirmation) ProtoMessage()               {}
func (*Confirmation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Confirmation) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

type Config struct {
	Consumer string `protobuf:"bytes,1,opt,name=consumer" json:"consumer,omitempty"`
	Topic    string `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Config) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *Config) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "pubsub.Message")
	proto.RegisterType((*Request)(nil), "pubsub.Request")
	proto.RegisterType((*StartRequest)(nil), "pubsub.StartRequest")
	proto.RegisterType((*Confirmation)(nil), "pubsub.Confirmation")
	proto.RegisterType((*Config)(nil), "pubsub.Config")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MessageSource service

type MessageSourceClient interface {
	Consume(ctx context.Context, opts ...grpc.CallOption) (MessageSource_ConsumeClient, error)
}

type messageSourceClient struct {
	cc *grpc.ClientConn
}

func NewMessageSourceClient(cc *grpc.ClientConn) MessageSourceClient {
	return &messageSourceClient{cc}
}

func (c *messageSourceClient) Consume(ctx context.Context, opts ...grpc.CallOption) (MessageSource_ConsumeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MessageSource_serviceDesc.Streams[0], c.cc, "/pubsub.MessageSource/Consume", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageSourceConsumeClient{stream}
	return x, nil
}

type MessageSource_ConsumeClient interface {
	Send(*Request) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type messageSourceConsumeClient struct {
	grpc.ClientStream
}

func (x *messageSourceConsumeClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageSourceConsumeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MessageSource service

type MessageSourceServer interface {
	Consume(MessageSource_ConsumeServer) error
}

func RegisterMessageSourceServer(s *grpc.Server, srv MessageSourceServer) {
	s.RegisterService(&_MessageSource_serviceDesc, srv)
}

func _MessageSource_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageSourceServer).Consume(&messageSourceConsumeServer{stream})
}

type MessageSource_ConsumeServer interface {
	Send(*Message) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type messageSourceConsumeServer struct {
	grpc.ServerStream
}

func (x *messageSourceConsumeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageSourceConsumeServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MessageSource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pubsub.MessageSource",
	HandlerType: (*MessageSourceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _MessageSource_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proximo.proto",
}

func init() { proto.RegisterFile("proximo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x71, 0x80, 0x84, 0x1e, 0x29, 0x48, 0x56, 0x87, 0xa8, 0x53, 0x65, 0x31, 0x64, 0x21,
	0x82, 0xb2, 0x20, 0x26, 0x44, 0x59, 0x18, 0x58, 0xdc, 0x4f, 0x90, 0x3f, 0x26, 0xf2, 0x90, 0x5c,
	0xf0, 0x1f, 0x89, 0x85, 0xef, 0x8e, 0xea, 0xb8, 0xc5, 0xde, 0xfc, 0x7c, 0xef, 0xfd, 0xee, 0xce,
	0x86, 0xe5, 0xa4, 0xf0, 0x47, 0x0e, 0x58, 0x4d, 0x0a, 0x0d, 0xd2, 0x74, 0xb2, 0x8d, 0xb6, 0x0d,
	0xbb, 0x87, 0xec, 0x53, 0x68, 0x5d, 0xf7, 0x82, 0x52, 0xb8, 0xe8, 0x6a, 0x53, 0x17, 0x64, 0x43,
	0xca, 0x9c, 0xbb, 0x33, 0xbd, 0x81, 0x44, 0x76, 0x45, 0xb2, 0x21, 0xe5, 0x82, 0x27, 0xb2, 0x63,
	0xbf, 0x90, 0x71, 0xf1, 0x6d, 0x85, 0x36, 0xf4, 0x19, 0x72, 0x6d, 0x6a, 0x65, 0xbc, 0x76, 0xa6,
	0xeb, 0xed, 0xaa, 0x9a, 0xc1, 0xd5, 0x3e, 0xa8, 0xf1, 0xc8, 0x79, 0x48, 0xb6, 0x38, 0x7e, 0x49,
	0x35, 0xd4, 0x46, 0xe2, 0x58, 0x9c, 0xc7, 0xc9, 0x5d, 0x50, 0xe3, 0x91, 0x93, 0xbd, 0x42, 0x1e,
	0x72, 0xe9, 0x0a, 0x2e, 0x0d, 0x4e, 0xb2, 0x75, 0x33, 0x2f, 0xf8, 0x2c, 0xe8, 0x1a, 0xae, 0x5a,
	0x1c, 0xb5, 0x1d, 0x84, 0xf2, 0xa3, 0x9f, 0x34, 0xbb, 0x83, 0x3c, 0xe4, 0x1f, 0x08, 0x83, 0xee,
	0x3f, 0xde, 0x8f, 0x04, 0x27, 0xd8, 0x0b, 0xa4, 0xce, 0xd5, 0x47, 0x2c, 0x12, 0xb3, 0xfe, 0xbb,
	0x27, 0x41, 0xf7, 0xed, 0x1b, 0x2c, 0xfd, 0x8b, 0xee, 0xd1, 0xaa, 0x56, 0xd0, 0x47, 0xc8, 0x76,
	0x73, 0x84, 0xde, 0x1e, 0x77, 0xf4, 0x0b, 0xac, 0x4f, 0x17, 0x3e, 0xc2, 0xce, 0x4a, 0xf2, 0x40,
	0x9a, 0xd4, 0x7d, 0xd2, 0xd3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xbd, 0x35, 0xcf, 0xb5,
	0x01, 0x00, 0x00,
}
