// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/proximo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageSource_Consume_FullMethodName = "/proximo.MessageSource/Consume"
)

// MessageSourceClient is the client API for MessageSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Consumer types
type MessageSourceClient interface {
	Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumerRequest, Message], error)
}

type messageSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageSourceClient(cc grpc.ClientConnInterface) MessageSourceClient {
	return &messageSourceClient{cc}
}

func (c *messageSourceClient) Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumerRequest, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageSource_ServiceDesc.Streams[0], MessageSource_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumerRequest, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageSource_ConsumeClient = grpc.BidiStreamingClient[ConsumerRequest, Message]

// MessageSourceServer is the server API for MessageSource service.
// All implementations should embed UnimplementedMessageSourceServer
// for forward compatibility.
//
// Consumer types
type MessageSourceServer interface {
	Consume(grpc.BidiStreamingServer[ConsumerRequest, Message]) error
}

// UnimplementedMessageSourceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageSourceServer struct{}

func (UnimplementedMessageSourceServer) Consume(grpc.BidiStreamingServer[ConsumerRequest, Message]) error {
	return status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedMessageSourceServer) testEmbeddedByValue() {}

// UnsafeMessageSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageSourceServer will
// result in compilation errors.
type UnsafeMessageSourceServer interface {
	mustEmbedUnimplementedMessageSourceServer()
}

func RegisterMessageSourceServer(s grpc.ServiceRegistrar, srv MessageSourceServer) {
	// If the following call panics, it indicates UnimplementedMessageSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageSource_ServiceDesc, srv)
}

func _MessageSource_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageSourceServer).Consume(&grpc.GenericServerStream[ConsumerRequest, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageSource_ConsumeServer = grpc.BidiStreamingServer[ConsumerRequest, Message]

// MessageSource_ServiceDesc is the grpc.ServiceDesc for MessageSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proximo.MessageSource",
	HandlerType: (*MessageSourceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _MessageSource_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/proximo.proto",
}

const (
	MessageSink_Publish_FullMethodName = "/proximo.MessageSink/Publish"
)

// MessageSinkClient is the client API for MessageSink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Producer types
type MessageSinkClient interface {
	Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublisherRequest, Confirmation], error)
}

type messageSinkClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageSinkClient(cc grpc.ClientConnInterface) MessageSinkClient {
	return &messageSinkClient{cc}
}

func (c *messageSinkClient) Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublisherRequest, Confirmation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageSink_ServiceDesc.Streams[0], MessageSink_Publish_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublisherRequest, Confirmation]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageSink_PublishClient = grpc.BidiStreamingClient[PublisherRequest, Confirmation]

// MessageSinkServer is the server API for MessageSink service.
// All implementations should embed UnimplementedMessageSinkServer
// for forward compatibility.
//
// Producer types
type MessageSinkServer interface {
	Publish(grpc.BidiStreamingServer[PublisherRequest, Confirmation]) error
}

// UnimplementedMessageSinkServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageSinkServer struct{}

func (UnimplementedMessageSinkServer) Publish(grpc.BidiStreamingServer[PublisherRequest, Confirmation]) error {
	return status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedMessageSinkServer) testEmbeddedByValue() {}

// UnsafeMessageSinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageSinkServer will
// result in compilation errors.
type UnsafeMessageSinkServer interface {
	mustEmbedUnimplementedMessageSinkServer()
}

func RegisterMessageSinkServer(s grpc.ServiceRegistrar, srv MessageSinkServer) {
	// If the following call panics, it indicates UnimplementedMessageSinkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageSink_ServiceDesc, srv)
}

func _MessageSink_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageSinkServer).Publish(&grpc.GenericServerStream[PublisherRequest, Confirmation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageSink_PublishServer = grpc.BidiStreamingServer[PublisherRequest, Confirmation]

// MessageSink_ServiceDesc is the grpc.ServiceDesc for MessageSink service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageSink_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proximo.MessageSink",
	HandlerType: (*MessageSinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _MessageSink_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/proximo.proto",
}
