// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/proximo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Offset int32

const (
	Offset_OFFSET_DEFAULT Offset = 0
	Offset_OFFSET_NEWEST  Offset = 1
	Offset_OFFSET_OLDEST  Offset = 2
)

// Enum value maps for Offset.
var (
	Offset_name = map[int32]string{
		0: "OFFSET_DEFAULT",
		1: "OFFSET_NEWEST",
		2: "OFFSET_OLDEST",
	}
	Offset_value = map[string]int32{
		"OFFSET_DEFAULT": 0,
		"OFFSET_NEWEST":  1,
		"OFFSET_OLDEST":  2,
	}
)

func (x Offset) Enum() *Offset {
	p := new(Offset)
	*p = x
	return p
}

func (x Offset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Offset) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proximo_proto_enumTypes[0].Descriptor()
}

func (Offset) Type() protoreflect.EnumType {
	return &file_proto_proximo_proto_enumTypes[0]
}

func (x Offset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Offset.Descriptor instead.
func (Offset) EnumDescriptor() ([]byte, []int) {
	return file_proto_proximo_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_proximo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proximo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_proximo_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ConsumerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// expected if this is a start request
	StartRequest *StartConsumeRequest `protobuf:"bytes,2,opt,name=startRequest,proto3" json:"startRequest,omitempty"`
	// expected if this is a confirmation
	Confirmation  *Confirmation `protobuf:"bytes,3,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerRequest) Reset() {
	*x = ConsumerRequest{}
	mi := &file_proto_proximo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerRequest) ProtoMessage() {}

func (x *ConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proximo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerRequest.ProtoReflect.Descriptor instead.
func (*ConsumerRequest) Descriptor() ([]byte, []int) {
	return file_proto_proximo_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumerRequest) GetStartRequest() *StartConsumeRequest {
	if x != nil {
		return x.StartRequest
	}
	return nil
}

func (x *ConsumerRequest) GetConfirmation() *Confirmation {
	if x != nil {
		return x.Confirmation
	}
	return nil
}

type StartConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Consumer      string                 `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	InitialOffset Offset                 `protobuf:"varint,3,opt,name=initial_offset,json=initialOffset,proto3,enum=proximo.Offset" json:"initial_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartConsumeRequest) Reset() {
	*x = StartConsumeRequest{}
	mi := &file_proto_proximo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConsumeRequest) ProtoMessage() {}

func (x *StartConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proximo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConsumeRequest.ProtoReflect.Descriptor instead.
func (*StartConsumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_proximo_proto_rawDescGZIP(), []int{2}
}

func (x *StartConsumeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *StartConsumeRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *StartConsumeRequest) GetInitialOffset() Offset {
	if x != nil {
		return x.InitialOffset
	}
	return Offset_OFFSET_DEFAULT
}

type Confirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgID         string                 `protobuf:"bytes,1,opt,name=msgID,proto3" json:"msgID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirmation) Reset() {
	*x = Confirmation{}
	mi := &file_proto_proximo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation) ProtoMessage() {}

func (x *Confirmation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proximo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation.ProtoReflect.Descriptor instead.
func (*Confirmation) Descriptor() ([]byte, []int) {
	return file_proto_proximo_proto_rawDescGZIP(), []int{3}
}

func (x *Confirmation) GetMsgID() string {
	if x != nil {
		return x.MsgID
	}
	return ""
}

type PublisherRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// expected if this is a start request
	StartRequest *StartPublishRequest `protobuf:"bytes,2,opt,name=startRequest,proto3" json:"startRequest,omitempty"`
	// expected if this is a message
	Msg           *Message `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherRequest) Reset() {
	*x = PublisherRequest{}
	mi := &file_proto_proximo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherRequest) ProtoMessage() {}

func (x *PublisherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proximo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherRequest.ProtoReflect.Descriptor instead.
func (*PublisherRequest) Descriptor() ([]byte, []int) {
	return file_proto_proximo_proto_rawDescGZIP(), []int{4}
}

func (x *PublisherRequest) GetStartRequest() *StartPublishRequest {
	if x != nil {
		return x.StartRequest
	}
	return nil
}

func (x *PublisherRequest) GetMsg() *Message {
	if x != nil {
		return x.Msg
	}
	return nil
}

type StartPublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPublishRequest) Reset() {
	*x = StartPublishRequest{}
	mi := &file_proto_proximo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPublishRequest) ProtoMessage() {}

func (x *StartPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proximo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPublishRequest.ProtoReflect.Descriptor instead.
func (*StartPublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_proximo_proto_rawDescGZIP(), []int{5}
}

func (x *StartPublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

var File_proto_proximo_proto protoreflect.FileDescriptor

const file_proto_proximo_proto_rawDesc = "" +
	"\n" +
	"\x13proto/proximo.proto\x12\aproximo\"?\n" +
	"\aMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\"\x8e\x01\n" +
	"\x0fConsumerRequest\x12@\n" +
	"\fstartRequest\x18\x02 \x01(\v2\x1c.proximo.StartConsumeRequestR\fstartRequest\x129\n" +
	"\fconfirmation\x18\x03 \x01(\v2\x15.proximo.ConfirmationR\fconfirmation\"\x7f\n" +
	"\x13StartConsumeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1a\n" +
	"\bconsumer\x18\x02 \x01(\tR\bconsumer\x126\n" +
	"\x0einitial_offset\x18\x03 \x01(\x0e2\x0f.proximo.OffsetR\rinitialOffset\"$\n" +
	"\fConfirmation\x12\x14\n" +
	"\x05msgID\x18\x01 \x01(\tR\x05msgID\"x\n" +
	"\x10PublisherRequest\x12@\n" +
	"\fstartRequest\x18\x02 \x01(\v2\x1c.proximo.StartPublishRequestR\fstartRequest\x12\"\n" +
	"\x03msg\x18\x03 \x01(\v2\x10.proximo.MessageR\x03msg\"+\n" +
	"\x13StartPublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic*B\n" +
	"\x06Offset\x12\x12\n" +
	"\x0eOFFSET_DEFAULT\x10\x00\x12\x11\n" +
	"\rOFFSET_NEWEST\x10\x01\x12\x11\n" +
	"\rOFFSET_OLDEST\x10\x022L\n" +
	"\rMessageSource\x12;\n" +
	"\aConsume\x12\x18.proximo.ConsumerRequest\x1a\x10.proximo.Message\"\x00(\x010\x012P\n" +
	"\vMessageSink\x12A\n" +
	"\aPublish\x12\x19.proximo.PublisherRequest\x1a\x15.proximo.Confirmation\"\x00(\x010\x01B(Z&github.com/uw-labs/proximo/proto;protob\x06proto3"

var (
	file_proto_proximo_proto_rawDescOnce sync.Once
	file_proto_proximo_proto_rawDescData []byte
)

func file_proto_proximo_proto_rawDescGZIP() []byte {
	file_proto_proximo_proto_rawDescOnce.Do(func() {
		file_proto_proximo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proximo_proto_rawDesc), len(file_proto_proximo_proto_rawDesc)))
	})
	return file_proto_proximo_proto_rawDescData
}

var file_proto_proximo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proximo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_proximo_proto_goTypes = []any{
	(Offset)(0),                 // 0: proximo.Offset
	(*Message)(nil),             // 1: proximo.Message
	(*ConsumerRequest)(nil),     // 2: proximo.ConsumerRequest
	(*StartConsumeRequest)(nil), // 3: proximo.StartConsumeRequest
	(*Confirmation)(nil),        // 4: proximo.Confirmation
	(*PublisherRequest)(nil),    // 5: proximo.PublisherRequest
	(*StartPublishRequest)(nil), // 6: proximo.StartPublishRequest
}
var file_proto_proximo_proto_depIdxs = []int32{
	3, // 0: proximo.ConsumerRequest.startRequest:type_name -> proximo.StartConsumeRequest
	4, // 1: proximo.ConsumerRequest.confirmation:type_name -> proximo.Confirmation
	0, // 2: proximo.StartConsumeRequest.initial_offset:type_name -> proximo.Offset
	6, // 3: proximo.PublisherRequest.startRequest:type_name -> proximo.StartPublishRequest
	1, // 4: proximo.PublisherRequest.msg:type_name -> proximo.Message
	2, // 5: proximo.MessageSource.Consume:input_type -> proximo.ConsumerRequest
	5, // 6: proximo.MessageSink.Publish:input_type -> proximo.PublisherRequest
	1, // 7: proximo.MessageSource.Consume:output_type -> proximo.Message
	4, // 8: proximo.MessageSink.Publish:output_type -> proximo.Confirmation
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_proximo_proto_init() }
func file_proto_proximo_proto_init() {
	if File_proto_proximo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proximo_proto_rawDesc), len(file_proto_proximo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_proximo_proto_goTypes,
		DependencyIndexes: file_proto_proximo_proto_depIdxs,
		EnumInfos:         file_proto_proximo_proto_enumTypes,
		MessageInfos:      file_proto_proximo_proto_msgTypes,
	}.Build()
	File_proto_proximo_proto = out.File
	file_proto_proximo_proto_goTypes = nil
	file_proto_proximo_proto_depIdxs = nil
}
