# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proximo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proximo.proto',
  package='proximo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rproximo.proto\x12\x07proximo\"#\n\x07Message\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\n\n\x02id\x18\x02 \x01(\t\"r\n\x0f\x43onsumerRequest\x12\x32\n\x0cstartRequest\x18\x02 \x01(\x0b\x32\x1c.proximo.StartConsumeRequest\x12+\n\x0c\x63onfirmation\x18\x03 \x01(\x0b\x32\x15.proximo.Confirmation\"_\n\x13StartConsumeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08\x63onsumer\x18\x02 \x01(\t\x12\'\n\x0einitial_offset\x18\x03 \x01(\x0e\x32\x0f.proximo.Offset\"\x1d\n\x0c\x43onfirmation\x12\r\n\x05msgID\x18\x01 \x01(\t\"e\n\x10PublisherRequest\x12\x32\n\x0cstartRequest\x18\x02 \x01(\x0b\x32\x1c.proximo.StartPublishRequest\x12\x1d\n\x03msg\x18\x03 \x01(\x0b\x32\x10.proximo.Message\"$\n\x13StartPublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t*B\n\x06Offset\x12\x12\n\x0eOFFSET_DEFAULT\x10\x00\x12\x11\n\rOFFSET_NEWEST\x10\x01\x12\x11\n\rOFFSET_OLDEST\x10\x02\x32L\n\rMessageSource\x12;\n\x07\x43onsume\x12\x18.proximo.ConsumerRequest\x1a\x10.proximo.Message\"\x00(\x01\x30\x01\x32P\n\x0bMessageSink\x12\x41\n\x07Publish\x12\x19.proximo.PublisherRequest\x1a\x15.proximo.Confirmation\"\x00(\x01\x30\x01\x62\x06proto3')
)

_OFFSET = _descriptor.EnumDescriptor(
  name='Offset',
  full_name='proximo.Offset',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFFSET_DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFFSET_NEWEST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFFSET_OLDEST', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=448,
  serialized_end=514,
)
_sym_db.RegisterEnumDescriptor(_OFFSET)

Offset = enum_type_wrapper.EnumTypeWrapper(_OFFSET)
OFFSET_DEFAULT = 0
OFFSET_NEWEST = 1
OFFSET_OLDEST = 2



_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='proximo.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='proximo.Message.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='proximo.Message.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=61,
)


_CONSUMERREQUEST = _descriptor.Descriptor(
  name='ConsumerRequest',
  full_name='proximo.ConsumerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startRequest', full_name='proximo.ConsumerRequest.startRequest', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confirmation', full_name='proximo.ConsumerRequest.confirmation', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=177,
)


_STARTCONSUMEREQUEST = _descriptor.Descriptor(
  name='StartConsumeRequest',
  full_name='proximo.StartConsumeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='proximo.StartConsumeRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='consumer', full_name='proximo.StartConsumeRequest.consumer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initial_offset', full_name='proximo.StartConsumeRequest.initial_offset', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=274,
)


_CONFIRMATION = _descriptor.Descriptor(
  name='Confirmation',
  full_name='proximo.Confirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgID', full_name='proximo.Confirmation.msgID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=305,
)


_PUBLISHERREQUEST = _descriptor.Descriptor(
  name='PublisherRequest',
  full_name='proximo.PublisherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startRequest', full_name='proximo.PublisherRequest.startRequest', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='proximo.PublisherRequest.msg', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=408,
)


_STARTPUBLISHREQUEST = _descriptor.Descriptor(
  name='StartPublishRequest',
  full_name='proximo.StartPublishRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='proximo.StartPublishRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=446,
)

_CONSUMERREQUEST.fields_by_name['startRequest'].message_type = _STARTCONSUMEREQUEST
_CONSUMERREQUEST.fields_by_name['confirmation'].message_type = _CONFIRMATION
_STARTCONSUMEREQUEST.fields_by_name['initial_offset'].enum_type = _OFFSET
_PUBLISHERREQUEST.fields_by_name['startRequest'].message_type = _STARTPUBLISHREQUEST
_PUBLISHERREQUEST.fields_by_name['msg'].message_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['ConsumerRequest'] = _CONSUMERREQUEST
DESCRIPTOR.message_types_by_name['StartConsumeRequest'] = _STARTCONSUMEREQUEST
DESCRIPTOR.message_types_by_name['Confirmation'] = _CONFIRMATION
DESCRIPTOR.message_types_by_name['PublisherRequest'] = _PUBLISHERREQUEST
DESCRIPTOR.message_types_by_name['StartPublishRequest'] = _STARTPUBLISHREQUEST
DESCRIPTOR.enum_types_by_name['Offset'] = _OFFSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'proximo_pb2'
  # @@protoc_insertion_point(class_scope:proximo.Message)
  ))
_sym_db.RegisterMessage(Message)

ConsumerRequest = _reflection.GeneratedProtocolMessageType('ConsumerRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERREQUEST,
  __module__ = 'proximo_pb2'
  # @@protoc_insertion_point(class_scope:proximo.ConsumerRequest)
  ))
_sym_db.RegisterMessage(ConsumerRequest)

StartConsumeRequest = _reflection.GeneratedProtocolMessageType('StartConsumeRequest', (_message.Message,), dict(
  DESCRIPTOR = _STARTCONSUMEREQUEST,
  __module__ = 'proximo_pb2'
  # @@protoc_insertion_point(class_scope:proximo.StartConsumeRequest)
  ))
_sym_db.RegisterMessage(StartConsumeRequest)

Confirmation = _reflection.GeneratedProtocolMessageType('Confirmation', (_message.Message,), dict(
  DESCRIPTOR = _CONFIRMATION,
  __module__ = 'proximo_pb2'
  # @@protoc_insertion_point(class_scope:proximo.Confirmation)
  ))
_sym_db.RegisterMessage(Confirmation)

PublisherRequest = _reflection.GeneratedProtocolMessageType('PublisherRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUBLISHERREQUEST,
  __module__ = 'proximo_pb2'
  # @@protoc_insertion_point(class_scope:proximo.PublisherRequest)
  ))
_sym_db.RegisterMessage(PublisherRequest)

StartPublishRequest = _reflection.GeneratedProtocolMessageType('StartPublishRequest', (_message.Message,), dict(
  DESCRIPTOR = _STARTPUBLISHREQUEST,
  __module__ = 'proximo_pb2'
  # @@protoc_insertion_point(class_scope:proximo.StartPublishRequest)
  ))
_sym_db.RegisterMessage(StartPublishRequest)



_MESSAGESOURCE = _descriptor.ServiceDescriptor(
  name='MessageSource',
  full_name='proximo.MessageSource',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=516,
  serialized_end=592,
  methods=[
  _descriptor.MethodDescriptor(
    name='Consume',
    full_name='proximo.MessageSource.Consume',
    index=0,
    containing_service=None,
    input_type=_CONSUMERREQUEST,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGESOURCE)

DESCRIPTOR.services_by_name['MessageSource'] = _MESSAGESOURCE


_MESSAGESINK = _descriptor.ServiceDescriptor(
  name='MessageSink',
  full_name='proximo.MessageSink',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=594,
  serialized_end=674,
  methods=[
  _descriptor.MethodDescriptor(
    name='Publish',
    full_name='proximo.MessageSink.Publish',
    index=0,
    containing_service=None,
    input_type=_PUBLISHERREQUEST,
    output_type=_CONFIRMATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGESINK)

DESCRIPTOR.services_by_name['MessageSink'] = _MESSAGESINK

# @@protoc_insertion_point(module_scope)
