// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proximo.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proximo {

  /// <summary>Holder for reflection information generated from proximo.proto</summary>
  public static partial class ProximoReflection {

    #region Descriptor
    /// <summary>File descriptor for proximo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProximoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1wcm94aW1vLnByb3RvEgdwcm94aW1vIiMKB01lc3NhZ2USDAoEZGF0YRgB",
            "IAEoDBIKCgJpZBgCIAEoCSJyCg9Db25zdW1lclJlcXVlc3QSMgoMc3RhcnRS",
            "ZXF1ZXN0GAIgASgLMhwucHJveGltby5TdGFydENvbnN1bWVSZXF1ZXN0EisK",
            "DGNvbmZpcm1hdGlvbhgDIAEoCzIVLnByb3hpbW8uQ29uZmlybWF0aW9uIjYK",
            "E1N0YXJ0Q29uc3VtZVJlcXVlc3QSDQoFdG9waWMYASABKAkSEAoIY29uc3Vt",
            "ZXIYAiABKAkiHQoMQ29uZmlybWF0aW9uEg0KBW1zZ0lEGAEgASgJImUKEFB1",
            "Ymxpc2hlclJlcXVlc3QSMgoMc3RhcnRSZXF1ZXN0GAIgASgLMhwucHJveGlt",
            "by5TdGFydFB1Ymxpc2hSZXF1ZXN0Eh0KA21zZxgDIAEoCzIQLnByb3hpbW8u",
            "TWVzc2FnZSIkChNTdGFydFB1Ymxpc2hSZXF1ZXN0Eg0KBXRvcGljGAEgASgJ",
            "MkwKDU1lc3NhZ2VTb3VyY2USOwoHQ29uc3VtZRIYLnByb3hpbW8uQ29uc3Vt",
            "ZXJSZXF1ZXN0GhAucHJveGltby5NZXNzYWdlIgAoATABMlAKC01lc3NhZ2VT",
            "aW5rEkEKB1B1Ymxpc2gSGS5wcm94aW1vLlB1Ymxpc2hlclJlcXVlc3QaFS5w",
            "cm94aW1vLkNvbmZpcm1hdGlvbiIAKAEwAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proximo.Message), global::Proximo.Message.Parser, new[]{ "Data", "Id" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proximo.ConsumerRequest), global::Proximo.ConsumerRequest.Parser, new[]{ "StartRequest", "Confirmation" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proximo.StartConsumeRequest), global::Proximo.StartConsumeRequest.Parser, new[]{ "Topic", "Consumer" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proximo.Confirmation), global::Proximo.Confirmation.Parser, new[]{ "MsgID" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proximo.PublisherRequest), global::Proximo.PublisherRequest.Parser, new[]{ "StartRequest", "Msg" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proximo.StartPublishRequest), global::Proximo.StartPublishRequest.Parser, new[]{ "Topic" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Message : pb::IMessage<Message> {
    private static readonly pb::MessageParser<Message> _parser = new pb::MessageParser<Message>(() => new Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Message> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proximo.ProximoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Message() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Message(Message other) : this() {
      data_ = other.data_;
      id_ = other.id_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Message Clone() {
      return new Message(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Message);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Message other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      if (Id != other.Id) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Data);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Message other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Data = input.ReadBytes();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ConsumerRequest : pb::IMessage<ConsumerRequest> {
    private static readonly pb::MessageParser<ConsumerRequest> _parser = new pb::MessageParser<ConsumerRequest>(() => new ConsumerRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConsumerRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proximo.ProximoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConsumerRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConsumerRequest(ConsumerRequest other) : this() {
      StartRequest = other.startRequest_ != null ? other.StartRequest.Clone() : null;
      Confirmation = other.confirmation_ != null ? other.Confirmation.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConsumerRequest Clone() {
      return new ConsumerRequest(this);
    }

    /// <summary>Field number for the "startRequest" field.</summary>
    public const int StartRequestFieldNumber = 2;
    private global::Proximo.StartConsumeRequest startRequest_;
    /// <summary>
    /// expected if this is a start request
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proximo.StartConsumeRequest StartRequest {
      get { return startRequest_; }
      set {
        startRequest_ = value;
      }
    }

    /// <summary>Field number for the "confirmation" field.</summary>
    public const int ConfirmationFieldNumber = 3;
    private global::Proximo.Confirmation confirmation_;
    /// <summary>
    /// expected if this is a confirmation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proximo.Confirmation Confirmation {
      get { return confirmation_; }
      set {
        confirmation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConsumerRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConsumerRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(StartRequest, other.StartRequest)) return false;
      if (!object.Equals(Confirmation, other.Confirmation)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (startRequest_ != null) hash ^= StartRequest.GetHashCode();
      if (confirmation_ != null) hash ^= Confirmation.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (startRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(StartRequest);
      }
      if (confirmation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Confirmation);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (startRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartRequest);
      }
      if (confirmation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Confirmation);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConsumerRequest other) {
      if (other == null) {
        return;
      }
      if (other.startRequest_ != null) {
        if (startRequest_ == null) {
          startRequest_ = new global::Proximo.StartConsumeRequest();
        }
        StartRequest.MergeFrom(other.StartRequest);
      }
      if (other.confirmation_ != null) {
        if (confirmation_ == null) {
          confirmation_ = new global::Proximo.Confirmation();
        }
        Confirmation.MergeFrom(other.Confirmation);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 18: {
            if (startRequest_ == null) {
              startRequest_ = new global::Proximo.StartConsumeRequest();
            }
            input.ReadMessage(startRequest_);
            break;
          }
          case 26: {
            if (confirmation_ == null) {
              confirmation_ = new global::Proximo.Confirmation();
            }
            input.ReadMessage(confirmation_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class StartConsumeRequest : pb::IMessage<StartConsumeRequest> {
    private static readonly pb::MessageParser<StartConsumeRequest> _parser = new pb::MessageParser<StartConsumeRequest>(() => new StartConsumeRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StartConsumeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proximo.ProximoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartConsumeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartConsumeRequest(StartConsumeRequest other) : this() {
      topic_ = other.topic_;
      consumer_ = other.consumer_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartConsumeRequest Clone() {
      return new StartConsumeRequest(this);
    }

    /// <summary>Field number for the "topic" field.</summary>
    public const int TopicFieldNumber = 1;
    private string topic_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Topic {
      get { return topic_; }
      set {
        topic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "consumer" field.</summary>
    public const int ConsumerFieldNumber = 2;
    private string consumer_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Consumer {
      get { return consumer_; }
      set {
        consumer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StartConsumeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StartConsumeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Topic != other.Topic) return false;
      if (Consumer != other.Consumer) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Topic.Length != 0) hash ^= Topic.GetHashCode();
      if (Consumer.Length != 0) hash ^= Consumer.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Topic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Topic);
      }
      if (Consumer.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Consumer);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Topic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Topic);
      }
      if (Consumer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Consumer);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StartConsumeRequest other) {
      if (other == null) {
        return;
      }
      if (other.Topic.Length != 0) {
        Topic = other.Topic;
      }
      if (other.Consumer.Length != 0) {
        Consumer = other.Consumer;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Topic = input.ReadString();
            break;
          }
          case 18: {
            Consumer = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Confirmation : pb::IMessage<Confirmation> {
    private static readonly pb::MessageParser<Confirmation> _parser = new pb::MessageParser<Confirmation>(() => new Confirmation());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Confirmation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proximo.ProximoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Confirmation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Confirmation(Confirmation other) : this() {
      msgID_ = other.msgID_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Confirmation Clone() {
      return new Confirmation(this);
    }

    /// <summary>Field number for the "msgID" field.</summary>
    public const int MsgIDFieldNumber = 1;
    private string msgID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MsgID {
      get { return msgID_; }
      set {
        msgID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Confirmation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Confirmation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgID != other.MsgID) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgID.Length != 0) hash ^= MsgID.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MsgID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MsgID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MsgID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MsgID);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Confirmation other) {
      if (other == null) {
        return;
      }
      if (other.MsgID.Length != 0) {
        MsgID = other.MsgID;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            MsgID = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PublisherRequest : pb::IMessage<PublisherRequest> {
    private static readonly pb::MessageParser<PublisherRequest> _parser = new pb::MessageParser<PublisherRequest>(() => new PublisherRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PublisherRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proximo.ProximoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PublisherRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PublisherRequest(PublisherRequest other) : this() {
      StartRequest = other.startRequest_ != null ? other.StartRequest.Clone() : null;
      Msg = other.msg_ != null ? other.Msg.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PublisherRequest Clone() {
      return new PublisherRequest(this);
    }

    /// <summary>Field number for the "startRequest" field.</summary>
    public const int StartRequestFieldNumber = 2;
    private global::Proximo.StartPublishRequest startRequest_;
    /// <summary>
    /// expected if this is a start request
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proximo.StartPublishRequest StartRequest {
      get { return startRequest_; }
      set {
        startRequest_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 3;
    private global::Proximo.Message msg_;
    /// <summary>
    /// expected if this is a message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proximo.Message Msg {
      get { return msg_; }
      set {
        msg_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PublisherRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PublisherRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(StartRequest, other.StartRequest)) return false;
      if (!object.Equals(Msg, other.Msg)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (startRequest_ != null) hash ^= StartRequest.GetHashCode();
      if (msg_ != null) hash ^= Msg.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (startRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(StartRequest);
      }
      if (msg_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Msg);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (startRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartRequest);
      }
      if (msg_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Msg);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PublisherRequest other) {
      if (other == null) {
        return;
      }
      if (other.startRequest_ != null) {
        if (startRequest_ == null) {
          startRequest_ = new global::Proximo.StartPublishRequest();
        }
        StartRequest.MergeFrom(other.StartRequest);
      }
      if (other.msg_ != null) {
        if (msg_ == null) {
          msg_ = new global::Proximo.Message();
        }
        Msg.MergeFrom(other.Msg);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 18: {
            if (startRequest_ == null) {
              startRequest_ = new global::Proximo.StartPublishRequest();
            }
            input.ReadMessage(startRequest_);
            break;
          }
          case 26: {
            if (msg_ == null) {
              msg_ = new global::Proximo.Message();
            }
            input.ReadMessage(msg_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class StartPublishRequest : pb::IMessage<StartPublishRequest> {
    private static readonly pb::MessageParser<StartPublishRequest> _parser = new pb::MessageParser<StartPublishRequest>(() => new StartPublishRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StartPublishRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proximo.ProximoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartPublishRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartPublishRequest(StartPublishRequest other) : this() {
      topic_ = other.topic_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StartPublishRequest Clone() {
      return new StartPublishRequest(this);
    }

    /// <summary>Field number for the "topic" field.</summary>
    public const int TopicFieldNumber = 1;
    private string topic_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Topic {
      get { return topic_; }
      set {
        topic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StartPublishRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StartPublishRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Topic != other.Topic) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Topic.Length != 0) hash ^= Topic.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Topic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Topic);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Topic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Topic);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StartPublishRequest other) {
      if (other == null) {
        return;
      }
      if (other.Topic.Length != 0) {
        Topic = other.Topic;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Topic = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
