// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proximo.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Offset int32

const (
	Offset_OFFSET_DEFAULT Offset = 0
	Offset_OFFSET_NEWEST  Offset = 1
	Offset_OFFSET_OLDEST  Offset = 2
)

var Offset_name = map[int32]string{
	0: "OFFSET_DEFAULT",
	1: "OFFSET_NEWEST",
	2: "OFFSET_OLDEST",
}

var Offset_value = map[string]int32{
	"OFFSET_DEFAULT": 0,
	"OFFSET_NEWEST":  1,
	"OFFSET_OLDEST":  2,
}

func (x Offset) String() string {
	return proto.EnumName(Offset_name, int32(x))
}

func (Offset) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a91ca4463dd05b0a, []int{0}
}

type Message struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_a91ca4463dd05b0a, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ConsumerRequest struct {
	// expected if this is a start request
	StartRequest *StartConsumeRequest `protobuf:"bytes,2,opt,name=startRequest,proto3" json:"startRequest,omitempty"`
	// expected if this is a confirmation
	Confirmation         *Confirmation `protobuf:"bytes,3,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConsumerRequest) Reset()         { *m = ConsumerRequest{} }
func (m *ConsumerRequest) String() string { return proto.CompactTextString(m) }
func (*ConsumerRequest) ProtoMessage()    {}
func (*ConsumerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a91ca4463dd05b0a, []int{1}
}

func (m *ConsumerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumerRequest.Unmarshal(m, b)
}
func (m *ConsumerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumerRequest.Marshal(b, m, deterministic)
}
func (m *ConsumerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerRequest.Merge(m, src)
}
func (m *ConsumerRequest) XXX_Size() int {
	return xxx_messageInfo_ConsumerRequest.Size(m)
}
func (m *ConsumerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerRequest proto.InternalMessageInfo

func (m *ConsumerRequest) GetStartRequest() *StartConsumeRequest {
	if m != nil {
		return m.StartRequest
	}
	return nil
}

func (m *ConsumerRequest) GetConfirmation() *Confirmation {
	if m != nil {
		return m.Confirmation
	}
	return nil
}

type StartConsumeRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Consumer             string   `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	InitialOffset        Offset   `protobuf:"varint,3,opt,name=initial_offset,json=initialOffset,proto3,enum=proximo.Offset" json:"initial_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartConsumeRequest) Reset()         { *m = StartConsumeRequest{} }
func (m *StartConsumeRequest) String() string { return proto.CompactTextString(m) }
func (*StartConsumeRequest) ProtoMessage()    {}
func (*StartConsumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a91ca4463dd05b0a, []int{2}
}

func (m *StartConsumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartConsumeRequest.Unmarshal(m, b)
}
func (m *StartConsumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartConsumeRequest.Marshal(b, m, deterministic)
}
func (m *StartConsumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartConsumeRequest.Merge(m, src)
}
func (m *StartConsumeRequest) XXX_Size() int {
	return xxx_messageInfo_StartConsumeRequest.Size(m)
}
func (m *StartConsumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartConsumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartConsumeRequest proto.InternalMessageInfo

func (m *StartConsumeRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *StartConsumeRequest) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *StartConsumeRequest) GetInitialOffset() Offset {
	if m != nil {
		return m.InitialOffset
	}
	return Offset_OFFSET_DEFAULT
}

type Confirmation struct {
	MsgID                string   `protobuf:"bytes,1,opt,name=msgID,proto3" json:"msgID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Confirmation) Reset()         { *m = Confirmation{} }
func (m *Confirmation) String() string { return proto.CompactTextString(m) }
func (*Confirmation) ProtoMessage()    {}
func (*Confirmation) Descriptor() ([]byte, []int) {
	return fileDescriptor_a91ca4463dd05b0a, []int{3}
}

func (m *Confirmation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Confirmation.Unmarshal(m, b)
}
func (m *Confirmation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Confirmation.Marshal(b, m, deterministic)
}
func (m *Confirmation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Confirmation.Merge(m, src)
}
func (m *Confirmation) XXX_Size() int {
	return xxx_messageInfo_Confirmation.Size(m)
}
func (m *Confirmation) XXX_DiscardUnknown() {
	xxx_messageInfo_Confirmation.DiscardUnknown(m)
}

var xxx_messageInfo_Confirmation proto.InternalMessageInfo

func (m *Confirmation) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

type PublisherRequest struct {
	// expected if this is a start request
	StartRequest *StartPublishRequest `protobuf:"bytes,2,opt,name=startRequest,proto3" json:"startRequest,omitempty"`
	// expected if this is a message
	Msg                  *Message `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublisherRequest) Reset()         { *m = PublisherRequest{} }
func (m *PublisherRequest) String() string { return proto.CompactTextString(m) }
func (*PublisherRequest) ProtoMessage()    {}
func (*PublisherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a91ca4463dd05b0a, []int{4}
}

func (m *PublisherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublisherRequest.Unmarshal(m, b)
}
func (m *PublisherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublisherRequest.Marshal(b, m, deterministic)
}
func (m *PublisherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublisherRequest.Merge(m, src)
}
func (m *PublisherRequest) XXX_Size() int {
	return xxx_messageInfo_PublisherRequest.Size(m)
}
func (m *PublisherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublisherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublisherRequest proto.InternalMessageInfo

func (m *PublisherRequest) GetStartRequest() *StartPublishRequest {
	if m != nil {
		return m.StartRequest
	}
	return nil
}

func (m *PublisherRequest) GetMsg() *Message {
	if m != nil {
		return m.Msg
	}
	return nil
}

type StartPublishRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartPublishRequest) Reset()         { *m = StartPublishRequest{} }
func (m *StartPublishRequest) String() string { return proto.CompactTextString(m) }
func (*StartPublishRequest) ProtoMessage()    {}
func (*StartPublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a91ca4463dd05b0a, []int{5}
}

func (m *StartPublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartPublishRequest.Unmarshal(m, b)
}
func (m *StartPublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartPublishRequest.Marshal(b, m, deterministic)
}
func (m *StartPublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartPublishRequest.Merge(m, src)
}
func (m *StartPublishRequest) XXX_Size() int {
	return xxx_messageInfo_StartPublishRequest.Size(m)
}
func (m *StartPublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartPublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartPublishRequest proto.InternalMessageInfo

func (m *StartPublishRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterEnum("proximo.Offset", Offset_name, Offset_value)
	proto.RegisterType((*Message)(nil), "proximo.Message")
	proto.RegisterType((*ConsumerRequest)(nil), "proximo.ConsumerRequest")
	proto.RegisterType((*StartConsumeRequest)(nil), "proximo.StartConsumeRequest")
	proto.RegisterType((*Confirmation)(nil), "proximo.Confirmation")
	proto.RegisterType((*PublisherRequest)(nil), "proximo.PublisherRequest")
	proto.RegisterType((*StartPublishRequest)(nil), "proximo.StartPublishRequest")
}

func init() { proto.RegisterFile("proximo.proto", fileDescriptor_a91ca4463dd05b0a) }

var fileDescriptor_a91ca4463dd05b0a = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x7d, 0xc9, 0xd3, 0x17, 0xdf, 0x7d, 0x49, 0x1a, 0xaf, 0x0a, 0xb1, 0xb8, 0x28, 0x83, 0x8b,
	0xa2, 0x58, 0x24, 0x82, 0x20, 0x6e, 0xac, 0x6d, 0x0a, 0x42, 0xb5, 0x65, 0x52, 0x71, 0x59, 0xd2,
	0x34, 0xad, 0x83, 0x4d, 0xa6, 0x66, 0x26, 0xd0, 0x9d, 0xff, 0xc0, 0xdf, 0x2c, 0x99, 0x4c, 0x43,
	0xaa, 0xd9, 0xb8, 0xcb, 0xb9, 0x1f, 0xe7, 0x9e, 0x7b, 0xee, 0x04, 0x9c, 0x63, 0xc1, 0x4f, 0x2c,
	0xe3, 0xa3, 0x63, 0xc1, 0x25, 0x47, 0x4b, 0x43, 0xf2, 0x0a, 0xac, 0xcf, 0xa9, 0x10, 0xf1, 0x3e,
	0x45, 0x84, 0x7b, 0xdb, 0x58, 0xc6, 0xbe, 0x31, 0x30, 0x86, 0x36, 0x55, 0xdf, 0xe8, 0x82, 0xc9,
	0xb6, 0xbe, 0x39, 0x30, 0x86, 0xb7, 0xd4, 0x64, 0x5b, 0xf2, 0xdb, 0x80, 0xde, 0x84, 0xe7, 0xa2,
	0xcc, 0xd2, 0x82, 0xa6, 0x3f, 0xcb, 0x54, 0x48, 0xfc, 0x00, 0xb6, 0x90, 0x71, 0x21, 0x35, 0x56,
	0xd5, 0x77, 0xc1, 0xb3, 0xd1, 0x79, 0x62, 0x54, 0x25, 0x75, 0x93, 0xae, 0xa1, 0x17, 0x1d, 0xf8,
	0x0e, 0xec, 0x84, 0xe7, 0x3b, 0x56, 0x64, 0xb1, 0x64, 0x3c, 0xf7, 0xaf, 0x15, 0xc3, 0x93, 0x86,
	0x61, 0xd2, 0x4a, 0xd2, 0x8b, 0x52, 0xf2, 0x0b, 0x1e, 0x75, 0xf0, 0xe3, 0x63, 0xb8, 0x2f, 0xf9,
	0x91, 0x25, 0x6a, 0x99, 0x5b, 0x5a, 0x03, 0xec, 0xc3, 0x83, 0x44, 0x8b, 0xd7, 0x3b, 0x35, 0x18,
	0xdf, 0x82, 0xcb, 0x72, 0x26, 0x59, 0x7c, 0x58, 0xf3, 0xdd, 0x4e, 0xa4, 0x52, 0xa9, 0x70, 0x83,
	0x5e, 0xa3, 0x62, 0xa1, 0xc2, 0xd4, 0xd1, 0x65, 0x35, 0x24, 0xcf, 0xc1, 0x6e, 0xcb, 0xab, 0x26,
	0x67, 0x62, 0xff, 0x69, 0x7a, 0x9e, 0xac, 0x00, 0x39, 0x81, 0xb7, 0x2c, 0x37, 0x07, 0x26, 0xbe,
	0xff, 0xa7, 0x6f, 0xba, 0xab, 0xdb, 0x37, 0x02, 0xd7, 0x99, 0xd8, 0x6b, 0xbb, 0xbc, 0xa6, 0x51,
	0x1f, 0x94, 0x56, 0x49, 0xf2, 0x52, 0x1b, 0x74, 0x49, 0xd4, 0x6d, 0xd0, 0x8b, 0x8f, 0x70, 0x53,
	0xaf, 0x85, 0x08, 0xee, 0x62, 0x36, 0x8b, 0xc2, 0xd5, 0x7a, 0x1a, 0xce, 0xc6, 0x5f, 0xe7, 0x2b,
	0xef, 0x0a, 0x1f, 0x82, 0xa3, 0x63, 0x5f, 0xc2, 0x6f, 0x61, 0xb4, 0xf2, 0x8c, 0x56, 0x68, 0x31,
	0x9f, 0x56, 0x21, 0x33, 0x98, 0x83, 0xa3, 0x05, 0x44, 0xbc, 0x2c, 0x92, 0x14, 0xdf, 0x83, 0xa5,
	0xaf, 0x83, 0x7e, 0xfb, 0xa4, 0xed, 0x47, 0xd4, 0xff, 0x47, 0x3d, 0xb9, 0x1a, 0x1a, 0xaf, 0x8d,
	0x60, 0x09, 0x77, 0x67, 0x36, 0x96, 0xff, 0xc0, 0x31, 0x58, 0x7a, 0x11, 0x7c, 0xda, 0x74, 0xfc,
	0xed, 0x6c, 0xbf, 0xfb, 0xe5, 0xd4, 0x8c, 0x9b, 0x1b, 0xf5, 0x07, 0xbc, 0xf9, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x44, 0x70, 0xab, 0xad, 0x12, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageSourceClient is the client API for MessageSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageSourceClient interface {
	Consume(ctx context.Context, opts ...grpc.CallOption) (MessageSource_ConsumeClient, error)
}

type messageSourceClient struct {
	cc *grpc.ClientConn
}

func NewMessageSourceClient(cc *grpc.ClientConn) MessageSourceClient {
	return &messageSourceClient{cc}
}

func (c *messageSourceClient) Consume(ctx context.Context, opts ...grpc.CallOption) (MessageSource_ConsumeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MessageSource_serviceDesc.Streams[0], "/proximo.MessageSource/Consume", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageSourceConsumeClient{stream}
	return x, nil
}

type MessageSource_ConsumeClient interface {
	Send(*ConsumerRequest) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type messageSourceConsumeClient struct {
	grpc.ClientStream
}

func (x *messageSourceConsumeClient) Send(m *ConsumerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageSourceConsumeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageSourceServer is the server API for MessageSource service.
type MessageSourceServer interface {
	Consume(MessageSource_ConsumeServer) error
}

func RegisterMessageSourceServer(s *grpc.Server, srv MessageSourceServer) {
	s.RegisterService(&_MessageSource_serviceDesc, srv)
}

func _MessageSource_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageSourceServer).Consume(&messageSourceConsumeServer{stream})
}

type MessageSource_ConsumeServer interface {
	Send(*Message) error
	Recv() (*ConsumerRequest, error)
	grpc.ServerStream
}

type messageSourceConsumeServer struct {
	grpc.ServerStream
}

func (x *messageSourceConsumeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageSourceConsumeServer) Recv() (*ConsumerRequest, error) {
	m := new(ConsumerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MessageSource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proximo.MessageSource",
	HandlerType: (*MessageSourceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _MessageSource_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proximo.proto",
}

// MessageSinkClient is the client API for MessageSink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageSinkClient interface {
	Publish(ctx context.Context, opts ...grpc.CallOption) (MessageSink_PublishClient, error)
}

type messageSinkClient struct {
	cc *grpc.ClientConn
}

func NewMessageSinkClient(cc *grpc.ClientConn) MessageSinkClient {
	return &messageSinkClient{cc}
}

func (c *messageSinkClient) Publish(ctx context.Context, opts ...grpc.CallOption) (MessageSink_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MessageSink_serviceDesc.Streams[0], "/proximo.MessageSink/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageSinkPublishClient{stream}
	return x, nil
}

type MessageSink_PublishClient interface {
	Send(*PublisherRequest) error
	Recv() (*Confirmation, error)
	grpc.ClientStream
}

type messageSinkPublishClient struct {
	grpc.ClientStream
}

func (x *messageSinkPublishClient) Send(m *PublisherRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageSinkPublishClient) Recv() (*Confirmation, error) {
	m := new(Confirmation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageSinkServer is the server API for MessageSink service.
type MessageSinkServer interface {
	Publish(MessageSink_PublishServer) error
}

func RegisterMessageSinkServer(s *grpc.Server, srv MessageSinkServer) {
	s.RegisterService(&_MessageSink_serviceDesc, srv)
}

func _MessageSink_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageSinkServer).Publish(&messageSinkPublishServer{stream})
}

type MessageSink_PublishServer interface {
	Send(*Confirmation) error
	Recv() (*PublisherRequest, error)
	grpc.ServerStream
}

type messageSinkPublishServer struct {
	grpc.ServerStream
}

func (x *messageSinkPublishServer) Send(m *Confirmation) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageSinkPublishServer) Recv() (*PublisherRequest, error) {
	m := new(PublisherRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MessageSink_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proximo.MessageSink",
	HandlerType: (*MessageSinkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _MessageSink_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proximo.proto",
}
